name: Build Ganjybird APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Android APK
        uses: p0lybi0s/love-android-action@v1.3.1
        with:
          app_name: "Ganjybird"
          bundle_id: "com.druiz.ganjybird"
          # Aqu√≠ configuramos tus iconos y splash screen
          icon_file: "game_icon.png"
          version_name: "1.0.0"
          version_code: 1

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Ganjybird-Release-APK
          path: "*.apk"
